namespace Tinycast.Features.Emoji;

public sealed record EmojiItem(string Glyph, string Name, string Group);

public static class EmojiCatalog
{
    public static IReadOnlyList<EmojiItem> All { get; } =
    [
        E("😀", "grinning face", "Smileys"),
        E("😃", "grinning face with big eyes", "Smileys"),
        E("😄", "grinning face with smiling eyes", "Smileys"),
        E("😁", "beaming face", "Smileys"),
        E("😅", "grinning face with sweat", "Smileys"),
        E("😂", "face with tears of joy", "Smileys"),
        E("🤣", "rolling on the floor laughing", "Smileys"),
        E("😊", "smiling face", "Smileys"),
        E("😇", "smiling face with halo", "Smileys"),
        E("🙂", "slightly smiling face", "Smileys"),
        E("😉", "winking face", "Smileys"),
        E("😍", "smiling face with heart eyes", "Smileys"),
        E("😘", "face blowing a kiss", "Smileys"),
        E("😜", "winking face with tongue", "Smileys"),
        E("🤔", "thinking face", "Smileys"),
        E("😐", "neutral face", "Smileys"),
        E("😴", "sleeping face", "Smileys"),
        E("😢", "crying face", "Smileys"),
        E("😭", "loudly crying face", "Smileys"),
        E("😡", "pouting face", "Smileys"),
        E("🤯", "exploding head", "Smileys"),
        E("😎", "smiling face with sunglasses", "Smileys"),
        E("🤩", "star-struck", "Smileys"),
        E("🥳", "partying face", "Smileys"),
        E("😤", "face with steam", "Smileys"),
        E("😨", "fearful face", "Smileys"),
        E("🤗", "hugging face", "Smileys"),
        E("🤫", "shushing face", "Smileys"),
        E("🤭", "face with hand over mouth", "Smileys"),
        E("🫡", "saluting face", "Smileys"),
        E("👍", "thumbs up", "People"),
        E("👎", "thumbs down", "People"),
        E("👏", "clapping hands", "People"),
        E("🙏", "folded hands", "People"),
        E("👋", "waving hand", "People"),
        E("👌", "ok hand", "People"),
        E("✌️", "victory hand", "People"),
        E("🤞", "crossed fingers", "People"),
        E("💪", "flexed biceps", "People"),
        E("👀", "eyes", "People"),
        E("🧠", "brain", "People"),
        E("🧑‍💻", "technologist", "People"),
        E("🔥", "fire", "Symbols"),
        E("✅", "check mark", "Symbols"),
        E("❌", "cross mark", "Symbols"),
        E("⭐", "star", "Symbols"),
        E("💡", "light bulb", "Symbols"),
        E("🎉", "party popper", "Symbols"),
        E("❤️", "red heart", "Symbols"),
        E("💔", "broken heart", "Symbols"),
        E("✨", "sparkles", "Symbols"),
        E("⚡", "high voltage", "Symbols"),
        E("⚠️", "warning", "Symbols"),
        E("❗", "exclamation", "Symbols"),
        E("❓", "question", "Symbols"),
        E("💯", "hundred points", "Symbols"),
        E("🚀", "rocket", "Travel"),
        E("✈️", "airplane", "Travel"),
        E("🚗", "car", "Travel"),
        E("🚕", "taxi", "Travel"),
        E("🚌", "bus", "Travel"),
        E("🚂", "locomotive", "Travel"),
        E("🏠", "house", "Travel"),
        E("🏢", "office", "Travel"),
        E("💻", "laptop", "Objects"),
        E("⌨️", "keyboard", "Objects"),
        E("📱", "mobile phone", "Objects"),
        E("📁", "file folder", "Objects"),
        E("📂", "open folder", "Objects"),
        E("📌", "pushpin", "Objects"),
        E("📝", "memo", "Objects"),
        E("🔍", "magnifying glass", "Objects"),
        E("🗓️", "calendar", "Objects"),
        E("⏰", "alarm clock", "Objects"),
        E("📦", "package", "Objects"),
        E("🔑", "key", "Objects"),
        E("🔒", "locked", "Objects"),
        E("📎", "paperclip", "Objects"),
        E("📚", "books", "Objects"),
        E("🌙", "crescent moon", "Nature"),
        E("☀️", "sun", "Nature"),
        E("⭐", "star", "Nature"),
        E("🌈", "rainbow", "Nature"),
        E("🌸", "cherry blossom", "Nature"),
        E("🍀", "four leaf clover", "Nature"),
        E("🐶", "dog", "Nature"),
        E("🐱", "cat", "Nature"),
        E("🦊", "fox", "Nature"),
        E("🐻", "bear", "Nature"),
        E("☕", "hot beverage", "Food"),
        E("🍵", "tea", "Food"),
        E("🍺", "beer", "Food"),
        E("🍷", "wine", "Food"),
        E("🍕", "pizza", "Food"),
        E("🍔", "hamburger", "Food"),
        E("🍟", "fries", "Food"),
        E("🍣", "sushi", "Food"),
        E("🍩", "doughnut", "Food"),
        E("🎂", "cake", "Food"),
        E("🍎", "apple", "Food"),
        E("🎵", "musical note", "Symbols"),
        E("🎬", "clapper board", "Objects"),
        E("📷", "camera", "Objects"),
        E("🎮", "video game", "Objects"),
        E("🏆", "trophy", "Objects"),
        E("🎯", "bullseye", "Objects"),
        E("📬", "mailbox", "Objects"),
        E("🔗", "link", "Symbols"),
        E("🆕", "new", "Symbols"),
        E("🆓", "free", "Symbols"),
    ];

    public static IReadOnlyList<EmojiItem> Search(string query)
    {
        if (string.IsNullOrWhiteSpace(query))
            return All;
        return All.Where(e =>
                e.Name.Contains(query, StringComparison.OrdinalIgnoreCase)
                || e.Group.Contains(query, StringComparison.OrdinalIgnoreCase)
                || e.Glyph.Contains(query))
            .ToList();
    }

    static EmojiItem E(string glyph, string name, string group) => new(glyph, name, group);
}
