#!/usr/bin/env python3
"""Generate EmojiData.generated.cs from Unicode emoji-test + CLDR annotations."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

GROUP_MAP = {
    "Smileys & Emotion": "Smileys",
    "People & Body": "People",
    "Animals & Nature": "Nature",
    "Food & Drink": "Food",
    "Activities": "Activities",
    "Travel & Places": "Travel",
    "Objects": "Objects",
    "Symbols": "Symbols",
    "Flags": "Flags",
}

TINTABLE = {
    "👍", "👎", "👏", "🙏", "👋", "👌", "✌️", "🤞", "💪", "✋", "🤚", "🖐️",
    "🖖", "🫱", "🫲", "🫳", "🫴", "👈", "👉", "👆", "🖕", "👇", "☝️", "🫵",
    "👍", "👎", "✊", "👊", "🤛", "🤜", "👏", "🫶", "🙌", "👐", "🤲", "🤝",
    "🙏", "✍️", "💅", "🤳", "💃", "🕺", "🧍", "🧎", "🏃", "🚶", "🧑", "👶",
    "🧒", "👦", "👧", "👩", "👨", "👴", "👵", "🙍", "🙎", "🙅", "🙆", "💁",
    "🙋", "🧏", "🙇", "🤦", "🤷", "👮", "🕵️", "💂", "🥷", "👷", "🫅", "🤴",
    "👸", "👳", "👲", "🧕", "🤵", "👰", "🤰", "🤱", "👼", "🎅", "🤶", "🦸",
    "🦹", "🧙", "🧚", "🧛", "🧜", "🧝", "💆", "💇", "🧖", "🧗", "🧘", "🛀",
    "🛌", "👭", "👫", "👬", "💏", "💑", "🗣️", "👤", "👥",
}

EXTRA = {
    "👍": ["+1", "like", "yes", "thumbs up"],
    "👎": ["-1", "no", "thumbs down"],
    "🎂": ["birthday", "cake"],
    "🙏": ["pray", "prayer", "thanks", "folded hands"],
    "🔥": ["hot", "lit", "fire"],
    "❤️": ["love", "heart", "red heart"],
    "😂": ["lol", "joy"],
    "✅": ["check", "done", "yes"],
    "🎉": ["party", "tada", "celebrate"],
}


def parse_annotations(path: Path) -> dict[str, list[str]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    table = (
        data.get("annotations", {}).get("annotations")
        or data.get("annotations")
        or {}
    )
    out: dict[str, list[str]] = {}
    for glyph, payload in table.items():
        words: list[str] = []
        if isinstance(payload, dict):
            for key in ("default", "tts"):
                value = payload.get(key)
                if isinstance(value, list):
                    words.extend(str(v) for v in value)
                elif isinstance(value, str):
                    words.append(value)
        out[glyph] = words
    return out


def is_skin_variant(codepoints: list[str]) -> bool:
    tones = {cp.upper() for cp in codepoints}
    return any(cp in tones for cp in ("1F3FB", "1F3FC", "1F3FD", "1F3FE", "1F3FF"))


def csharp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def keywords_for(glyph: str, name: str, annotations: dict[str, list[str]]) -> list[str]:
    words: list[str] = []
    seen: set[str] = set()

    def add(raw: str) -> None:
        text = raw.strip().lower()
        if not text or text in seen or text == name:
            return
        seen.add(text)
        words.append(text)

    for part in re.split(r"[,\s]+", name):
        add(part)
    for extra in annotations.get(glyph, []):
        for part in extra.split("|"):
            add(part)
            for token in re.split(r"[,\s]+", part):
                add(token)
    for extra in EXTRA.get(glyph, []):
        add(extra)
    return words


def main() -> int:
    repo = Path(__file__).resolve().parents[1]
    emoji_test = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    annotations_path = Path(sys.argv[2]) if len(sys.argv) > 2 else None
    if emoji_test is None or annotations_path is None:
        print("usage: gen-emoji.py emoji-test.txt annotations.json", file=sys.stderr)
        return 2

    annotations = parse_annotations(annotations_path)
    group = "Symbols"
    items: list[tuple[str, str, str, list[str], bool]] = []
    seen_glyphs: set[str] = set()
    line_re = re.compile(
        r"^([0-9A-F ]+);\s+fully-qualified\s+#\s+(\S+)\s+E[0-9.]+\s+(.+)$"
    )
    for raw in emoji_test.read_text(encoding="utf-8").splitlines():
        if raw.startswith("# group:"):
            group = GROUP_MAP.get(raw.split(":", 1)[1].strip(), "Symbols")
            continue
        match = line_re.match(raw)
        if not match:
            continue
        codepoints = match.group(1).split()
        if is_skin_variant(codepoints):
            continue
        glyph = match.group(2)
        name = match.group(3).strip().lower()
        if glyph in seen_glyphs:
            continue
        seen_glyphs.add(glyph)
        words = keywords_for(glyph, name, annotations)
        can_tint = glyph in TINTABLE or any(cp == "1F44D" for cp in codepoints)
        items.append((glyph, name, group, words, can_tint))

    out = repo / "src" / "Relay.Core" / "Features" / "Emoji" / "EmojiData.generated.cs"
    lines = [
        "// <auto-generated />",
        "namespace Relay.Features.Emoji;",
        "",
        "public static partial class EmojiCatalog",
        "{",
        "    public static IReadOnlyList<EmojiItem> All { get; } =",
        "    [",
    ]
    for glyph, name, group_name, words, can_tint in items:
        kw = ", ".join(csharp_string(w) for w in words)
        tint = "true" if can_tint else "false"
        lines.append(
            f"        new({csharp_string(glyph)}, {csharp_string(name)}, {csharp_string(group_name)}, [{kw}], {tint}),"
        )
    lines.append("    ];")
    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(items)} emoji to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
